//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_todo
    {
        public int id { get; set; }
        public string Tittle { get; set; }
        public string description { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
